# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\"\x10\n\x0eGetDataRequest\"D\n\x0c\x44\x61taResponse\x12\x12\n\nresponseId\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x01\x12\x12\n\nSensorType\x18\x03 \x01(\x05\x32:\n\rWorkerService\x12)\n\x07GetData\x12\x0f.GetDataRequest\x1a\r.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDATAREQUEST']._serialized_start=16
  _globals['_GETDATAREQUEST']._serialized_end=32
  _globals['_DATARESPONSE']._serialized_start=34
  _globals['_DATARESPONSE']._serialized_end=102
  _globals['_WORKERSERVICE']._serialized_start=104
  _globals['_WORKERSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
